[package]
name = "Rustfuzz"
version = "0.1.0"
authors = ["arekkusu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10.9"
tokio = { version = "0.2", features = ["full"] }
clap = "2.33.3"
